# Generated by Django 2.1.3 on 2019-09-29 02:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('conta', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Destino',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_turistico', models.CharField(max_length=100)),
                ('pais', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                ('bairro', models.CharField(max_length=100)),
                ('cep', models.CharField(max_length=100)),
                ('agencia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='conta.Agencia')),
            ],
        ),
        migrations.CreateModel(
            name='Excursao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.IntegerField(choices=[(1, 'Excursão'), (2, 'Bate volta')], default=1)),
                ('situacao', models.IntegerField(default=1)),
                ('titulo', models.CharField(max_length=50)),
                ('descricao', models.CharField(max_length=100)),
                ('horario_inicio', models.DateTimeField()),
                ('horario_fim', models.DateTimeField()),
                ('origem', models.CharField(max_length=20)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('agencia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='conta.Agencia')),
                ('destino', models.ManyToManyField(to='excursao.Destino')),
                ('usuario_cadastro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
