# Generated by Django 2.1.3 on 2019-10-26 01:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('conta', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destino',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_turistico', models.CharField(max_length=100)),
                ('pais', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                ('bairro', models.CharField(max_length=100)),
                ('cep', models.CharField(max_length=100)),
                ('agencia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='conta.Agencia')),
            ],
        ),
        migrations.CreateModel(
            name='Excursao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.IntegerField(choices=[(1, 'Excursão'), (2, 'Bate volta')], default=1)),
                ('situacao', models.IntegerField(default=1)),
                ('titulo', models.CharField(max_length=50)),
                ('descricao', models.CharField(max_length=100)),
                ('horario_inicio', models.DateTimeField()),
                ('horario_fim', models.DateTimeField()),
                ('origem', models.CharField(max_length=20)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('agencia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='conta.Agencia')),
                ('destino', models.ManyToManyField(to='excursao.Destino')),
                ('usuario_cadastro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Orcamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='PrestadorServico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('cnpj_cpf', models.CharField(max_length=50)),
                ('pessoa_juridica', models.BooleanField(null=True)),
                ('cadastur', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('telefone', models.CharField(max_length=50)),
                ('endereco', models.CharField(max_length=50)),
                ('horario_funcionamento', models.CharField(max_length=50)),
                ('agencia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='conta.Agencia')),
            ],
        ),
        migrations.CreateModel(
            name='Roteiro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='TipoPrestadorServico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TipoServico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Transporte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=50)),
                ('marca', models.CharField(max_length=50)),
                ('ano', models.IntegerField(null=True)),
                ('poltronas', models.IntegerField(null=True)),
                ('banheiro', models.BooleanField(blank=True, default=False, null=True)),
                ('frigobar', models.BooleanField(blank=True, default=False, null=True)),
                ('ar_condicionado', models.BooleanField(blank=True, default=False, null=True)),
                ('som', models.BooleanField(blank=True, default=False, null=True)),
                ('tv', models.BooleanField(blank=True, default=False, null=True)),
                ('observacao', models.CharField(max_length=200)),
                ('agencia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='conta.Agencia')),
                ('prestador_servico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='excursao.PrestadorServico')),
            ],
        ),
        migrations.AddField(
            model_name='prestadorservico',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='excursao.TipoPrestadorServico'),
        ),
    ]
