# Generated by Django 2.1.3 on 2019-01-29 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Excursao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.IntegerField(choices=[(1, 'Excursão'), (2, 'Bate volta')], default=1)),
                ('situacao', models.IntegerField(default=1)),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.TextField(default='')),
                ('horario_inicio', models.DateTimeField()),
                ('horario_fim', models.DateTimeField()),
                ('origem', models.CharField(max_length=100)),
                ('destino', models.CharField(max_length=100)),
            ],
        ),
    ]
