# Generated by Django 2.1.3 on 2019-10-16 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excursao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestadorservico',
            name='nome',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
