# Generated by Django 2.1.3 on 2020-04-14 11:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('conta', '0011_contacttravelagency_whatsapp'),
        ('excursao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destiny',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('neighborhood', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=100)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('registration_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('travel_agency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='conta.TravelAgency')),
            ],
        ),
        migrations.CreateModel(
            name='Estimate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.IntegerField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('selected', models.BooleanField(blank=True, default=False, null=True)),
                ('details', models.CharField(max_length=200)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='EstimateTransportDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estimate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='excursao.Estimate')),
            ],
        ),
        migrations.CreateModel(
            name='Excursion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('details', models.CharField(max_length=100)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('origin', models.CharField(max_length=20)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('destiny', models.ManyToManyField(to='excursao.Destiny')),
            ],
        ),
        migrations.CreateModel(
            name='ExcursionSituation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.PositiveIntegerField()),
                ('active', models.NullBooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='ExcursionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.PositiveIntegerField()),
                ('active', models.NullBooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='ServiceProvider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('cnpj_cpf', models.CharField(max_length=50)),
                ('legal_person', models.BooleanField(null=True)),
                ('cadastur', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('cell_phone', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('business_hours', models.CharField(max_length=50)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('registration_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceProviderType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=50)),
                ('brand', models.CharField(max_length=50)),
                ('year', models.IntegerField(null=True)),
                ('seats', models.IntegerField(null=True)),
                ('bathroom', models.BooleanField(blank=True, default=False, null=True)),
                ('minibar', models.BooleanField(blank=True, default=False, null=True)),
                ('air_conditioning', models.BooleanField(blank=True, default=False, null=True)),
                ('sound', models.BooleanField(blank=True, default=False, null=True)),
                ('tv', models.BooleanField(blank=True, default=False, null=True)),
                ('details', models.CharField(max_length=200)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('provider_service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='excursao.ServiceProvider')),
                ('registration_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('travel_agency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='conta.TravelAgency')),
            ],
        ),
        migrations.CreateModel(
            name='TravelItinerary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('paid', models.BooleanField(blank=True, default=False, null=True)),
                ('inclusive', models.BooleanField(blank=True, default=False, null=True)),
                ('cost', models.IntegerField()),
                ('details', models.CharField(max_length=200)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('excursion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='excursao.Excursion')),
                ('registration_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('travel_agency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='conta.TravelAgency')),
            ],
        ),
        migrations.RemoveField(
            model_name='destino',
            name='agencia',
        ),
        migrations.RemoveField(
            model_name='excursao',
            name='agencia',
        ),
        migrations.RemoveField(
            model_name='excursao',
            name='destino',
        ),
        migrations.RemoveField(
            model_name='excursao',
            name='usuario_cadastro',
        ),
        migrations.RemoveField(
            model_name='orcamento',
            name='agencia',
        ),
        migrations.RemoveField(
            model_name='orcamento',
            name='excursao',
        ),
        migrations.RemoveField(
            model_name='orcamento',
            name='prestador_servico',
        ),
        migrations.RemoveField(
            model_name='orcamento',
            name='tipo_prestador_servico',
        ),
        migrations.RemoveField(
            model_name='orcamentodetalhestransporte',
            name='orcamento',
        ),
        migrations.RemoveField(
            model_name='orcamentodetalhestransporte',
            name='transporte',
        ),
        migrations.RemoveField(
            model_name='prestadorservico',
            name='agencia',
        ),
        migrations.RemoveField(
            model_name='prestadorservico',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='roteiro',
            name='agencia',
        ),
        migrations.RemoveField(
            model_name='roteiro',
            name='excursao',
        ),
        migrations.DeleteModel(
            name='SituacaoExcusao',
        ),
        migrations.DeleteModel(
            name='TipoExcusao',
        ),
        migrations.DeleteModel(
            name='TipoServico',
        ),
        migrations.RemoveField(
            model_name='transporte',
            name='agencia',
        ),
        migrations.RemoveField(
            model_name='transporte',
            name='prestador_servico',
        ),
        migrations.DeleteModel(
            name='Destino',
        ),
        migrations.DeleteModel(
            name='Excursao',
        ),
        migrations.DeleteModel(
            name='Orcamento',
        ),
        migrations.DeleteModel(
            name='OrcamentoDetalhesTransporte',
        ),
        migrations.DeleteModel(
            name='PrestadorServico',
        ),
        migrations.DeleteModel(
            name='Roteiro',
        ),
        migrations.DeleteModel(
            name='TipoPrestadorServico',
        ),
        migrations.DeleteModel(
            name='Transporte',
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='service_provider_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='excursao.ServiceProviderType'),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='travel_agency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='conta.TravelAgency'),
        ),
        migrations.AddField(
            model_name='excursion',
            name='excursion_situation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='excursao.ExcursionSituation'),
        ),
        migrations.AddField(
            model_name='excursion',
            name='excursion_type',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='excursao.ExcursionType'),
        ),
        migrations.AddField(
            model_name='excursion',
            name='registration_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='excursion',
            name='travel_agency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='conta.TravelAgency'),
        ),
        migrations.AddField(
            model_name='estimatetransportdetails',
            name='transport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='excursao.Transport'),
        ),
        migrations.AddField(
            model_name='estimate',
            name='excursion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='excursao.Excursion'),
        ),
        migrations.AddField(
            model_name='estimate',
            name='registration_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='estimate',
            name='service_provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='excursao.ServiceProvider'),
        ),
        migrations.AddField(
            model_name='estimate',
            name='service_provider_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='excursao.ServiceProviderType'),
        ),
        migrations.AddField(
            model_name='estimate',
            name='travel_agency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='conta.TravelAgency'),
        ),
    ]
