# Generated by Django 2.1.3 on 2019-10-26 03:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conta', '0001_initial'),
        ('excursao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrcamentoTransporte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cotacao', models.IntegerField()),
                ('km', models.IntegerField()),
                ('horario_partida', models.DateTimeField()),
                ('horario_chegada', models.DateTimeField()),
                ('observacao', models.CharField(max_length=100)),
                ('agencia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='conta.Agencia')),
                ('excursao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='excursao.Excursao')),
                ('prestador_servico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='excursao.PrestadorServico')),
                ('transporte', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='excursao.Transporte')),
            ],
        ),
    ]
