# Generated by Django 2.1.3 on 2020-04-15 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excursao', '0002_auto_20200414_0849'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimate',
            name='name',
            field=models.CharField(default='name default', max_length=50),
            preserve_default=False,
        ),
    ]
