# Generated by Django 2.1.3 on 2019-10-17 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excursao', '0002_prestadorservico_nome'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoPrestadorServico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=20)),
            ],
        ),
    ]
