# Generated by Django 2.1.3 on 2019-11-18 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conta', '0001_initial'),
        ('excursao', '0002_orcamentotransporte'),
    ]

    operations = [
        migrations.AddField(
            model_name='roteiro',
            name='agencia',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='conta.Agencia'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roteiro',
            name='custo',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roteiro',
            name='excursao',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='excursao.Excursao'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roteiro',
            name='horario_fim',
            field=models.DateTimeField(default='2019-11-18 10:00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roteiro',
            name='horario_inicio',
            field=models.DateTimeField(default='2019-11-18 08:00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roteiro',
            name='incluso',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='roteiro',
            name='observacao',
            field=models.CharField(default='validação', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roteiro',
            name='pago',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
