# Generated by Django 2.1.3 on 2019-10-17 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('excursao', '0003_tipoprestadorservico'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestadorservico',
            name='categoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='excursao.TipoPrestadorServico'),
            preserve_default=False,
        ),
    ]
