# Generated by Django 2.1.3 on 2019-08-20 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('excursao', '0003_destino'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excursao',
            name='destino',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='excursao.Destino'),
        ),
    ]
