# Generated by Django 2.1.3 on 2019-11-20 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('excursao', '0004_auto_20191120_0733'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orcamentotransporte',
            name='agencia',
        ),
        migrations.RemoveField(
            model_name='orcamentotransporte',
            name='excursao',
        ),
        migrations.RemoveField(
            model_name='orcamentotransporte',
            name='prestador_servico',
        ),
        migrations.RemoveField(
            model_name='orcamentotransporte',
            name='transporte',
        ),
        migrations.DeleteModel(
            name='OrcamentoTransporte',
        ),
    ]
