# Generated by Django 2.1.3 on 2019-10-25 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excursao', '0005_auto_20191017_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transporte',
            name='ar_condicionado',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='transporte',
            name='banheiro',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='transporte',
            name='frigobar',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='transporte',
            name='som',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='transporte',
            name='tv',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
