# Generated by Django 2.1.3 on 2019-11-26 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('excursao', '0006_auto_20191126_2306'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orcamento',
            old_name='tipo_servico',
            new_name='tipo_prestador_servico',
        ),
    ]
