# Generated by Django 2.1.3 on 2019-08-20 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excursao', '0006_auto_20190820_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excursao',
            name='descricao',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='excursao',
            name='origem',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='excursao',
            name='titulo',
            field=models.CharField(max_length=50),
        ),
    ]
