# Generated by Django 2.1.3 on 2018-12-11 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.TextField(default='')),
                ('inicio_evento', models.DateTimeField()),
                ('fim_evento', models.DateTimeField()),
                ('origem', models.CharField(max_length=100)),
                ('destino', models.CharField(max_length=100)),
            ],
        ),
    ]
