# Generated by Django 2.1.3 on 2019-01-29 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_cadastur', models.CharField(max_length=10)),
                ('cnpj_cpf', models.CharField(max_length=14)),
                ('nome_juridico', models.TextField(max_length=30)),
                ('nome_fantasia', models.TextField(max_length=30)),
                ('nome_responsavel', models.TextField(max_length=30)),
                ('cpf_responsavel', models.TextField(max_length=14)),
                ('agencia_fisica', models.BooleanField()),
                ('foto_perfil', models.ImageField(blank=True, null=True, upload_to='')),
                ('endereco', models.TextField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=11)),
                ('fan_page_oficial', models.URLField(blank=True, null=True)),
                ('instagram_oficial', models.URLField(blank=True, null=True)),
                ('site_oficial', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
