# Generated by Django 2.1.3 on 2019-09-11 10:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_juridico', models.CharField(max_length=100)),
                ('nome_fantasia', models.CharField(max_length=100)),
                ('cod_cadastur', models.CharField(max_length=10)),
                ('cnpj', models.CharField(max_length=14)),
                ('agencia_fisica', models.BooleanField()),
                ('foto_perfil', models.ImageField(blank=True, null=True, upload_to='')),
                ('endereco', models.CharField(max_length=200)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('usuario_cadastro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ContatoAgencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('contato', models.CharField(max_length=11)),
                ('fan_page_oficial', models.URLField(blank=True, null=True)),
                ('instagram_oficial', models.URLField(blank=True, null=True)),
                ('site_oficial', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContatoPessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('contato', models.CharField(max_length=11)),
                ('whatsapp', models.CharField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=14)),
            ],
        ),
    ]
