# Generated by Django 2.1.3 on 2019-09-12 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conta', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pessoa',
            old_name='id_agencia',
            new_name='agencia',
        ),
        migrations.RenameField(
            model_name='pessoa',
            old_name='id_usuario',
            new_name='usuario',
        ),
    ]
