# Generated by Django 2.1.3 on 2020-04-03 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='agency_travel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='conta.TravelAgency'),
            preserve_default=False,
        ),
    ]
