# Generated by Django 2.1.3 on 2019-01-29 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agencia',
            name='cpf_responsavel',
            field=models.CharField(max_length=14),
        ),
        migrations.AlterField(
            model_name='agencia',
            name='endereco',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='agencia',
            name='nome_fantasia',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='agencia',
            name='nome_juridico',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='agencia',
            name='nome_responsavel',
            field=models.CharField(max_length=100),
        ),
    ]
