# Generated by Django 2.1.3 on 2020-04-06 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conta', '0002_profile_agency_travel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacttravelagency',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='travelagency',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
