# Generated by Django 2.1.3 on 2020-04-06 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conta', '0003_auto_20200406_1230'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='travelagency',
            old_name='contact_id',
            new_name='contact',
        ),
        migrations.RenameField(
            model_name='travelagency',
            old_name='owner_id',
            new_name='owner',
        ),
    ]
