# Generated by Django 2.1.3 on 2020-04-06 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conta', '0005_auto_20200406_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelagency',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logo_agency'),
        ),
    ]
