# Generated by Django 2.1.3 on 2020-04-07 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conta', '0007_remove_travelagency_logo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='agency_travel_id',
            new_name='agency_travel',
        ),
    ]
