# Generated by Django 2.1.3 on 2020-04-21 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conta', '0011_contacttravelagency_whatsapp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='agency_travel',
            new_name='travel_agency',
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=30, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Determina se este usuário deve ser tratado como ativo.      Marque como inativo em vez de excluir contas.', verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Determina se o usuário é funcionário da agência associada no perfil', verbose_name='staff status'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_trusty',
            field=models.BooleanField(default=False, help_text='Determina se este usuário confirmou sua conta.', verbose_name='trusty'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=30, verbose_name='Sobrenome'),
        ),
    ]
